# Auto-generated by Terragrunt from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
network_name                  = "data-agent-vpc"
private_service_access_config = {
  enable_private_services_connection = false
  address_name                       = "private-ip-address"
  prefix_length                      = 16
}
subnets = [
  {
    subnet_name           = "data-agent-gke"
    subnet_ip             = "10.0.0.0/24"
    subnet_region         = "us-central1"
    subnet_private_access = "true"
    description           = "GKE nodes; address plan allows growth to 10.0.0.0/23"
  },
]

# === Optional (defaults from try() fallbacks) ===
auto_create_subnetworks                = false
bgp_always_compare_med                 = false
bgp_best_path_selection_mode           = "LEGACY"
delete_default_internet_gateway_routes = false
description                            = "network with gke cluster with data-agent"
egress_rules                           = []
enable_ipv6_ula                        = false
firewall_rules                         = []
ingress_rules                          = []
mtu                                    = 0
routes                                 = []
routing_mode                           = "GLOBAL"
secondary_ranges = {
  data-agent-gke = [
    {
      range_name    = "data-agent-gke-pods"
      ip_cidr_range = "10.0.16.0/20"
    },
    {
      range_name    = "data-agent-gke-services"
      ip_cidr_range = "10.0.48.0/24"
    },
  ]
}
shared_vpc_host                        = false
