apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-apps

resources:
  - namespace.yaml
  - payments-api/deployment.yaml
  - payments-api/service.yaml
  - payments-api/servicemonitor.yaml
  - recommend-svc/deployment.yaml
  - recommend-svc/service.yaml
  - recommend-svc/servicemonitor.yaml
  - catalog-svc/deployment.yaml
  - catalog-svc/service.yaml
  - loadgen/deployment.yaml

images:
  - name: payments-api
    newName: us-central1-docker.pkg.dev/data-agent-c4d5/demo-apps/payments-api
    newTag: demo
  - name: recommend-svc
    newName: us-central1-docker.pkg.dev/data-agent-c4d5/demo-apps/recommend-svc
    newTag: demo
