# Auto-generated by Terragrunt from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
repository_id = "demo-apps"

# === Optional (defaults from try() fallbacks) ===
cleanup_policies       = {}
cleanup_policy_dry_run = false
format                 = "DOCKER"
labels                 = {}
location               = "us-central1"
members                = {}
mode                   = "STANDARD_REPOSITORY"
