# Auto-generated by Terragrunt from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
names      = ["data-agent-tofu-state"]
# === Optional (defaults from try() fallbacks) ===
admins                   = []
autoclass                = {}
bucket_admins            = {}
bucket_creators          = {}
bucket_hmac_key_admins   = {}
bucket_lifecycle_rules   = {}
bucket_policy_only       = {}
bucket_storage_admins    = {}
bucket_viewers           = {}
cors                     = []
creators                 = []
custom_placement_config  = {}
default_event_based_hold = {}
encryption_key_names     = {}
folders                  = {}
force_destroy            = { tofu-state : true }
hierarchical_namespace   = {}
hmac_key_admins          = []
hmac_service_accounts    = {}
ip_filter                = {}
labels                   = {}
lifecycle_rules          = []
location                 = "EU"
logging                  = {}
prefix                   = ""
public_access_prevention = "enforced"
randomize_suffix         = false
retention_policy         = {}
set_admin_roles          = false
set_creator_roles        = false
set_hmac_access          = false
set_hmac_key_admin_roles = false
set_storage_admin_roles  = false
set_viewer_roles         = false
soft_delete_policy       = {}
storage_admins           = []
storage_class            = "STANDARD"
versioning               = {}
viewers                  = []
website                  = {}
