# Auto-generated by Terragrunt from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
name = "data-agent"
# ip_range_pods / ip_range_services: from vpc secondary_ranges on the GKE subnet (order: pods, then services). Override in values if needed.
# subnetwork comes from dependency.vpc.outputs.subnets_names (override subnetwork in values if you have multiple node subnets)

# === Optional (defaults from try() fallbacks) ===
add_cluster_firewall_rules               = false
add_master_webhook_firewall_rules        = false
add_shadow_firewall_rules                = false
additional_ip_range_pods                 = []
additive_vpc_scope_dns_domain            = ""
cluster_autoscaling = {
  enabled                     = false
  autoscaling_profile         = "BALANCED"
  max_cpu_cores               = 0
  min_cpu_cores               = 0
  max_memory_gb               = 0
  min_memory_gb               = 0
  gpu_resources               = []
  auto_repair                 = true
  auto_upgrade                = true
  disk_size                   = 100
  disk_type                   = "pd-standard"
  image_type                  = "COS_CONTAINERD"
  enable_secure_boot          = false
  enable_integrity_monitoring = true
}
cluster_dns_domain                       = ""
cluster_dns_provider                     = "PROVIDER_UNSPECIFIED"
cluster_dns_scope                        = "DNS_SCOPE_UNSPECIFIED"
cluster_resource_labels                  = {}
configure_ip_masq                        = false
create_service_account                   = true
database_encryption                      = []
datapath_provider                        = "DATAPATH_PROVIDER_UNSPECIFIED"
default_max_pods_per_node                = 110
deletion_protection                      = false
deploy_using_private_endpoint            = false
description                              = "gke for data-agent workshop"
disable_default_snat                     = false
disable_legacy_metadata_endpoints        = true
dns_cache                                = false
enable_binary_authorization              = false
enable_cilium_clusterwide_network_policy = false
enable_confidential_nodes                = false
enable_cost_allocation                   = false
enable_default_node_pools_metadata       = true
enable_gcfs                              = false
enable_mesh_certificates                 = false
enable_network_egress_export             = false
enable_private_endpoint                  = false
enable_private_nodes                     = true
enable_resource_consumption_export       = true
enable_secret_manager_addon              = false
enable_shielded_nodes                    = true
enable_tpu                               = false
enable_vertical_pod_autoscaling          = false
filestore_csi_driver                     = false
firewall_inbound_ports                   = ["8443", "9443", "15017"]
firewall_priority                        = 1000
gce_pd_csi_driver                        = true
grant_registry_access                    = true
horizontal_pod_autoscaling               = false
http_load_balancing                      = true
identity_namespace                       = "enabled"
initial_node_count                       = 1
ip_masq_link_local                       = false
ip_masq_resync_interval                  = "60s"
issue_client_certificate                 = false
kubernetes_version                       = "latest"
logging_service                          = "logging.googleapis.com/kubernetes"
maintenance_end_time                     = ""
maintenance_exclusions                   = []
maintenance_recurrence                   = ""
maintenance_start_time                   = "05:00"
master_authorized_networks = [
  {
    cidr_block   = "0.0.0.0/0"
    display_name = "lab-open-control-plane"
  },
]
master_global_access_enabled             = true
master_ipv4_cidr_block                   = "172.16.0.0/28"
monitoring_service                       = "monitoring.googleapis.com/kubernetes"
network_policy                           = false
network_policy_provider                  = "CALICO"
network_project_id                       = ""
network_tags                             = []
node_metadata                            = "GKE_METADATA"
node_pools = [
  {
    name         = "default-node-pool"
    machine_type = "e2-medium"
    min_count    = 1
    max_count    = 1
    auto_repair  = true
    auto_upgrade = true
  },
]
node_pools_cgroup_mode                   = {}
node_pools_labels                        = {}
node_pools_linux_node_configs_sysctls    = {}
node_pools_metadata                      = {}
node_pools_oauth_scopes                  = {}
node_pools_resource_labels               = {}
node_pools_resource_manager_tags         = {}
node_pools_tags                          = {}
node_pools_taints                        = {}
non_masquerade_cidrs                     = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
notification_config_topic                = ""
notification_filter_event_type           = []
region                                   = "us-central1"
regional                                 = false
registry_project_ids                     = []
release_channel                          = "REGULAR"
remove_default_node_pool                 = true
resource_usage_export_dataset_id         = ""
security_posture_mode                    = "DISABLED"
security_posture_vulnerability_mode      = "VULNERABILITY_DISABLED"
service_account                          = ""
service_account_name                     = ""
service_external_ips                     = false
shadow_firewall_rules_log_config = {
  metadata = "INCLUDE_ALL_METADATA"
}
shadow_firewall_rules_priority = 999
stack_type                     = "IPV4"
stub_domains                   = {}
upstream_nameservers           = []
windows_node_pools             = []
zones                          = ["us-central1-a"]
