# Auto-generated by Terragrunt from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# === Required ===
name = "data-agent-router"
nats = []

# === Optional (defaults from try() fallbacks) ===
encrypted_interconnect_router          = false
nat_gateway_name                       = "data-agent-nat"
nat_log_enable                         = true
nat_log_filter                         = "ERRORS_ONLY"
nat_source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
nat_subnetworks                        = []
region                                 = "us-central1"
