# Auto-generated by Terragrunt from the `values.*` references in this unit/stack.
# Populate each `"TODO"` entry with a real value before running terragrunt.
#
# Required values come first. These are referenced directly by the unit or
# stack, so terragrunt will fail until you fill them in.
#
# Optional values come next, pre-populated with the defaults pulled from each
# reference's `try(...)` fallback. Edit any you want to override, or delete
# lines you're happy leaving at the fallback.

# GKE provider fields come from dependency outputs (../project, ../gke) in terragrunt.hcl.
# Override here only if you need to point at a different cluster/project.

# === Optional (defaults from try() fallbacks) ===
chart_version   = "10.10.0"
helm_values     = {}
kubeconfig_path = "~/.kube/config"
namespace       = "argocd"
release_name    = "argocd"
timeout         = 600
wait            = true
